
# packer init .
# packer validate -evaluate-datasources .
# packer build -debug -var-file=variables.auto.pkrvars.hcl github_agent.windows.pkr.hcl
# or
# packer build . | tee output.out 2>&1
region = "us-west-2"
instance_type = "t2.xlarge"
root_volume_size_gb = 60
ssh_keypair_name = "cppalliance-us-west-2-kp"
ssh_private_key_file = "/root/.ssh/cppalliance-us-west-2-kp.pem"

custom_shell_commands = [
"cd C:\\",
"choco feature enable -n allowGlobalConfirmation",
"# if --version is mentioned, the version has been checked, and the package installed",
"# automatic",
"# choco install -y visualstudio2017buildtools --version 15.9.54.0",
"# Installing visualstudio2019 on the same image as 2022. Recommended to install in chronological order",
"choco install -y visualstudio2019buildtools",
"choco install visualstudio2019-workload-vctools --package-parameters \"--add Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64\" \"--add Microsoft.VisualStudio.Component.VC.v141.x86.x64\" \"--add Microsoft.VisualStudio.Component.VC.140\" -y ",
"choco install -y visualstudio2022buildtools --version 117.5.5.0",
"choco install -y 7zip.install --version 22.1",
"# automatic",
"# choco install -y chocolatey --version 1.31",
"# choco install -y chocolatey-compatibility.extension --version 1.0.0",
"# choco install -y chocolatey-core.extension --version 1.4.0",
"# choco install -y chocolatey-dotnetfx.extension --version 1.0.1",
"# choco install -y chocolatey-fastanswers.extension",
"# choco install -y chocolatey-visualstudio.extension --version 1.10.2",
"# choco install -y chocolatey-windowsupdate.extension --version 1.0.5",
"# cmake not in path without extra flag",
"choco install -y cmake.install --installargs '\"ADD_CMAKE_TO_PATH=System\"' --version 3.26.3",
"choco install -y curl --version 8.0.1",
"# choco install -y DotNet4.5.2 ",
"# choco install -y DotNet4.6 ",
"# choco install -y DotNet4.6-TargetPack ",
"# choco install -y DotNet4.6.1 ",
"choco install -y dotnetfx --version 4.8.0.20220524",
"choco install -y git.install --version 2.40.1",
"choco install -y hashdeep --version 4.4",
"choco install -y jq --version 1.6",
"# automatic",
"# choco install -y KB2919355 --version 1.0.20160915",
"# choco install -y KB2919442 --version 1.0.20160915",
"# choco install -y KB2999226 --version 1.0.20181019",
"# choco install -y KB3033929 --version 1.0.5",
"# choco install -y KB3035131 --version 1.0.3",
"choco install -y llvm --version 16.0.3",
"choco install -y microsoft-build-tools --version 15.0.26320.2",
"choco install -y mingw --version 12.2.0.03042023",
"# no:",
"# choco install -y netfx-4.5.1-devpack ",
"# choco install -y netfx-4.5.2-devpack",
"# choco install -y netfx-4.6.1-devpack",
"choco install -y  notepadplusplus --version 8.5.2",
"choco install -y  notepadplusplus.install --version 8.5.2",
"choco install -y rsync --version 6.2.8",
"choco install -y ruby --version 3.1.3.1",
"# automatic:",
"# choco install -y vcredist140 --version 14.34.31938",
"# choco install -y vcredist2015 --version 14.0.24215.20170201",
"choco install -y vcredist2017 --version 14.16.27033",
"choco install -y visualstudio-installer --version 2.0.3",
"# CHECK. DO THESE EXIST? ARE THEY PRESENT NOW?",
"# choco install -y visualstudio2022-workload-netcorebuildtools # doesn't exist",
"# choco install -y visualstudio2022-workload-vctools --version 1.0.0 # see below",
"# choco install -y visualstudio2022-workload-webbuildtools --version 1.0.0",
"choco install -y Wget --version 1.21.3",
"choco install -y windows-sdk-10.1 --version 10.1.18362.1",
"choco install -y winscp --version 5.21.8",
"choco install -y winscp.install --version 5.21.8",
"# on 2019 there was a wsl error. skip for now.",
"# choco install -y wsl",
"choco install -y python --version 3.11.3",
"New-Item -ItemType SymbolicLink -Path \"C:\\Git\" -Target \"C:\\Program Files\\Git\"",
"# Adding visualstudio2022",
"choco install visualstudio2022-workload-vctools --package-parameters \"--add Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64\" \"--add Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64\" \"--add Microsoft.VisualStudio.Component.VC.v141.x86.x64\" \"--add Microsoft.VisualStudio.Component.VC.140\" -y ",
"$${oldpath} = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment' -Name PATH).path",
"$${newpath} = \"C:\\Git\\usr\\bin;$${oldpath}\"",
"Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment' -Name PATH -Value $${newPath}",
"# These files needed by msvc 14.0:",
"copy \"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64\\rc.exe\" \"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x86\\rc.exe\"",
"copy \"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64\\rcdll.dll\" \"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x86\\rcdll.dll\"",

"net user /add Administrator2 Testwin1234!",
"net localgroup administrators Administrator2 /add",
"echo almost done",
"pwd"
]
